import { Component, OnInit } from '@angular/core';

const AFFIRMATIONS = [
  'Ich bin zufrieden und glücklich.',
  'Ich bin willkommen.',
  'Ich genüge mir immer.',
  'Ich bin ein liebenswerter Mensch.',
  'Ich brauche nichts zu tun um geliebt zu werden.',
  'Ich bin unschuldig.',
  'Ich bin wertvoll.',
  'Ich habe ein Recht auf meine Meinung.',
  'Ich habe ein Recht auf meine Gefühle.',
  'In mir finde ich alles was ich brauche.',
  'Ich bin ein Gewinner.',
  'Ich liebe mich wie ich bin.',
  'Ich brauche keine Schuldgefühle zu haben.',
  'Ich darf meine Wut ausdrücken.',
  'Ich bin nicht für alles verantwortlich.',
  `Ich habe das Recht: 'Ich weiss es nicht' zu sagen.`,
  `Ich habe das Recht 'Nein' zu sagen und muss mich dafür nicht rechtfertigen.`,
  'Ich habe das Recht andere um etwas zu bitten.',
  'Ich darf an mich gerichtete Bitten abschlagen.',
  'Ich habe das Recht anderen mitzuteilen wenn diese mich schlecht behandeln.',
  'Ich darf unzumutbare Anforderungen zurückweisen.',
  'Ich brauche meinen Stolz und Würde nicht verletzen zu lassen.',
  'Ich darf Fehler machen und mich irren.',
  'Ich brauche nicht von allen bewundert oder gemocht werden für alles was ich tue.',
  'Ich bin talentiert.',
  'Ich bin gut im Teilen.',
  'Ich verbessere mich ständig.',
  'Es gibt keine andere Person, die ich lieber wäre, als ich selbst.',
  'Alles, was ich mir wünsche, ist bereits in mir.',
  'Ich verdiene das Beste.',
  'Ich fühle mich besser und besser.',
  'Es gibt eine Menge, worauf ich stolz sein kann.',
  'Ich bin dafür geschaffen, Erfolg zu haben! Das ist in meiner Seelen-DNA.',
  'Heute werde ich ruhig und voller Vertrauen sein.',
  'Es gefällt mir am Morgen aufzuwachen und einen neuen Tag zu begrüssen.',
  'Es ist schön, so viele Menschen um mich zu haben, die mich dabei unterstützen, meinen Weg zu gehen.',
  'Ich kann mit schwierigen Situationen umgehen.',
  'Ich habe Vertrauen in mich selbst.',
  'Ich sehe mich selbst als schön, intelligent und voller Selbstvertrauen und so sehen mich auch die anderen.',
  'Ich bin schön.',
  'Mein Selbstvertrauen wird jeden Tag stärker.',
  'Ich bin kreativ.',
  'Ich geniesse die einzelnen Momente meines Lebens.',
  'Ich habe die Freiheit, mein Leben so zu leben, wie ich es möchte.',
  'Ich bin aufrichtig mir selbst und anderen gegenüber.',
  'Ich bin talentiert und intelligent.',
  'Ich nehme mich selbst ernst.',
  'Ich achte gut auf mich.',
  'Ich kann im Jetzt Dinge ändern, die ich ändern möchte.',
  'Ich übernehme Verantwortung für mein Leben.',
  'Ich bin wertvoll, unabhängig davon, wie ich mich gerade fühle.',
  'Ich gestalte mein Leben nach meinen Vorstellungen.',
  'Ich sehe das Gute in den Menschen um mich.',
  'Ich weiss, dass ich nicht perfekt bin und es nie sein werde, aber ich mag mich genau so, wie ich bin.',
  'Ich bin nett zu mir selbst.',
  'Ich kann Spass haben und das Leben geniessen.',
  'Ich bin ausgeruht und erholt.',
  'Ich bin in der Lage, meine Gefühle angemessen auszudrücken.',
  'Ich bin dankbar für all das Gute in meinem Leben.',
  'Ich bin okay.',
  'Ich bewege mich entschlossen und mit Selbstvertrauen.',
  'Ich bin eine liebende und fürsorgliche Person.',
  'Ich bewege mich in eine positive Richtung und komme meinen Zielen näher.',
  'Ich mag meine Gefühle.',
  'Ich wertschätze mich selbst.',
  'Ich bin gut genug.',
  'Ich vertraue mir.',
  'Ich tue mein Bestes und das ist gut.',
  'Ich verfüge über Ausdauer und Beharrlichkeit.',
  'Ich kann es geniessen unter Menschen zu sein, und Kontakt zu haben.',
  'Ich mag meinen Körper.',
  'Ich fühle mich ruhig und sicher.',
  'Alles was ich brauche, steht mir zur Verfügung.',
  'Ich bestimme, wie ich leben möchte.',
  'Ich tue immer mein Bestes.',
  'Mein Leben hat einen Sinn.',
  'Ich kenne meinen Wert.',
  'Ich bin entspannt.',
  'Ich versuche so gut wie ich kann, weise Entscheidungen zu treffen.',
  'Ich bin nett.',
  'Ich kann meine Träume verwirklichen.',
  'Ich will leben.',
  'Ich geniesse den Prozess des lernens, um all das zu erreichen, was ich mir vorgenommen habe.',
  'Ich glaube an mich selbst.',
  'Ich möchte leben.',
  'Ich habe Vertrauen.',
  'Ich nutze meine Möglichkeiten und Chancen.',
  'Ich bin gerne hier.',
  'Ich werde von Tag zu Tag stärker.',
  'Ich kann selbst entscheiden, was ich tun möchte.',
  'Ich entscheide mich, Dinge zu tun, die mir ein gutes Gefühl geben.',
  `Ich habe mich für mein Leben und meinen Weg entschieden und bin bereit,
  alles Nötige zu tun, um meine Ziele zu verwirklichen und glücklich zu werden.`,
  'Ich höre auf mich selbst.',
  'Es ist schön zu leben.',
  'Ich fühle mich ruhig und sicher Tag für Tag.',
  'Ich akzeptiere alle meine Gefühle als Teil von mir.',
  'Ich folge meinen Träumen.',
  'Ich bin dankbar für all das, was mir gegeben wurde.',
  'Alles was das Leben mir zu bieten hat, ist wundervoll und es ist mein täglicher Entscheid, das Schöne zu geniessen.',
  'Ich bin intelligent.',
  'Ich bin geschätzt.',
  'Ich habe die Kontrolle über mein Leben.',
  'Ich bin fair und aufrichtig gegenüber anderen.',
  'Heute ist mein Tag. Es gibt keinen anderen Menschen oder äussere Ereignisse, die diesen Tag ruinieren könnten.',
  'Ich mag mich.',
  'Ich sorge für Menschen, die mir etwas bedeuten und zeige ihnen, dass ich sie liebe und wertschätze.',
  'Ich akzeptiere mich selbst hier und jetzt.',
  'Ich bin ein guter Freund.',
  'Ich habe Zugang zu einer erstaunlichen und beeindruckenden Welt.',
  'Ich bin mutig.',
  'Ich treffe meine Entscheidungen und ich mag meine Entscheidungen.',
  'Ich wähle Liebe und Vertrauen.',
  'Ich mag Dinge, die mir ein gutes Gefühl geben.',
  'Ich wertschätze den Moment.',
  'Ich mache alles so gut ich nur kann.',
  'Ich verdiene es glücklich zu sein.',
  'Ich akzeptiere mich, so wie ich bin und ich mag mich.',
  'Ich bin geliebt.',
  'Ich liebe mich selbst.',
  'Ich habe Vertrauen in die Zukunft.',
  'Ich bin liebenswert.',
  'Ich erlaube mir selbst, grosse Träume zu haben.',
  'Ich liebe mich, genau so wie ich bin.',
  'Heute fühle ich mich gut.',
  'Ich habe Freunde, die mich mögen und die sich für mich interessieren - und ich mag meine Freunde und interessiere mich für sie.',
  'Ich bin gut, genau so wie ich bin.',
  'Heute wird alles gut gehen, ich fühle mich gut.',
  'Ich bin voller Energie.',
  'Heute ist der erste Tag vom Rest meines Lebens und ich kann die Richtung bestimmen.',
  'Ich fühle Vertrauen und Ausgeglichenheit.',
  'Ich halte meinen Kopf hoch.',
  'Ich geniesse das Leben.',
  'Es gibt keinen Ort, an dem ich lieber wäre.',
  'Jetzt ist ein neuer Moment.',
  'In meinem Leben und in mir selbst gibt es Stabilität.',
  'Es gefällt mir, andere zu unterstützen.',
  'Ich geniesse es gut auszusehen.',
  'Ich bin ruhig und entspannt.',
  'Mir stehen viele Möglichkeiten offen und ich treffe die bestmöglichsten Entscheidungen.',
  'Ich achte darauf, was ich möchte.',
  'Ich bin stark körperlich, psychisch und emotional.',
  'Ich bin ein guter Freund.',
  'Jetzt ist ein neuer Moment.',
  'Ich bleibe abstinent, egal was passiert.',
  'Ich habe meinen Helden gefunden, der bin ich.',
  'Ich bin mein bester Freund.',
  'Ich kann alles machen, was ich will.',
  'Ich mache dass wovor ich am meisten Angst habe, und dominiere meine Angst.',
  'Ich bin selbstsicher.',
  'Ich habe Selbstvertrauen.',
  'Ich habe Selbstwert.',
  'Ich liebe mich und akzeptiere mich wie ich bin.',
  'Ich fühle mich gut, ich darf mich gut fühlen.'
];

@Component({
  selector: 'app-affirmations',
  templateUrl: './affirmations.component.html',
  styleUrls: ['./affirmations.component.scss']
})
export class AffirmationsComponent implements OnInit {
  private static counter = 0;
  private colorList =  [
    '#63b598', '#ce7d78', '#ea9e70', '#a48a9e', '#c6e1e8', '#648177' , '#0d5ac1' ,
    '#f205e6' , '#1c0365' , '#14a9ad' , '#4ca2f9' , '#a4e43f' , '#d298e2' , '#6119d0',
    '#d2737d' , '#c0a43c' , '#f2510e' , '#651be6' , '#79806e' , '#61da5e' , '#cd2f00' ,
    '#9348af' , '#01ac53' , '#c5a4fb' , '#996635', '#b11573' , '#4bb473' , '#75d89e' ,
    '#2f3f94' , '#2f7b99' , '#da967d' , '#34891f' , '#b0d87b' , '#ca4751' , '#7e50a8' ,
    '#c4d647' , '#e0eeb8' , '#11dec1' , '#289812' , '#566ca0' , '#ffdbe1' , '#2f1179' ,
    '#935b6d' , '#916988' , '#513d98' , '#aead3a', '#9e6d71', '#4b5bdc', '#0cd36d',
    '#250662', '#cb5bea', '#228916', '#ac3e1b', '#df514a', '#539397', '#880977',
    '#f697c1', '#ba96ce', '#679c9d', '#c6c42c', '#5d2c52', '#48b41b', '#e1cf3b',
    '#5be4f0', '#57c4d8', '#a4d17a', '#225b8', '#be608b', '#96b00c', '#088baf',
    '#f158bf', '#e145ba', '#ee91e3', '#05d371', '#5426e0', '#4834d0', '#802234',
    '#6749e8', '#0971f0', '#8fb413', '#b2b4f0', '#c3c89d', '#c9a941', '#41d158',
    '#fb21a3', '#51aed9', '#5bb32d', '#807fb', '#21538e', '#89d534', '#d36647',
    '#7fb411', '#0023b8', '#3b8c2a', '#986b53', '#f50422', '#983f7a', '#ea24a3',
    '#79352c', '#521250', '#c79ed2', '#d6dd92', '#e33e52', '#b2be57', '#fa06ec',
    '#1bb699', '#6b2e5f', '#64820f', '#1c271', '#21538e', '#89d534', '#d36647',
    '#7fb411', '#0023b8', '#3b8c2a', '#986b53', '#f50422', '#983f7a', '#ea24a3',
    '#79352c', '#521250', '#c79ed2', '#d6dd92', '#e33e52', '#b2be57', '#fa06ec',
    '#1bb699', '#6b2e5f', '#64820f', '#1c271', '#9cb64a', '#996c48', '#9ab9b7',
    '#06e052', '#e3a481', '#0eb621', '#fc458e', '#b2db15', '#aa226d', '#792ed8',
    '#73872a', '#520d3a', '#cefcb8', '#a5b3d9', '#7d1d85', '#c4fd57', '#f1ae16',
    '#8fe22a', '#ef6e3c', '#243eeb', '#1dc18', '#dd93fd', '#3f8473', '#e7dbce',
    '#421f79', '#7a3d93', '#635f6d', '#93f2d7', '#9b5c2a', '#15b9ee', '#0f5997',
    '#409188', '#911e20', '#1350ce', '#10e5b1', '#fff4d7', '#cb2582', '#ce00be',
    '#32d5d6', '#17232', '#608572', '#c79bc2', '#00f87c', '#77772a', '#6995ba',
    '#fc6b57', '#f07815', '#8fd883', '#060e27', '#96e591', '#21d52e', '#d00043',
    '#b47162', '#1ec227', '#4f0f6f', '#1d1d58', '#947002', '#bde052', '#e08c56',
    '#28fcfd', '#bb09b', '#36486a', '#d02e29', '#1ae6db', '#3e464c', '#a84a8f',
    '#911e7e', '#3f16d9', '#0f525f', '#ac7c0a', '#b4c086', '#c9d730', '#30cc49',
    '#3d6751', '#fb4c03', '#640fc1', '#62c03e', '#d3493a', '#88aa0b', '#406df9',
    '#615af0', '#4be47', '#2a3434', '#4a543f', '#79bca0', '#a8b8d4', '#00efd4',
    '#7ad236', '#7260d8', '#1deaa7', '#06f43a', '#823c59', '#e3d94c', '#dc1c06',
    '#f53b2a', '#b46238', '#2dfff6', '#a82b89', '#1a8011', '#436a9f', '#1a806a',
    '#4cf09d', '#c188a2', '#67eb4b', '#b308d3', '#fc7e41', '#af3101', '#ff065',
    '#71b1f4', '#a2f8a5', '#e23dd0', '#d3486d', '#00f7f9', '#474893', '#3cec35',
    '#1c65cb', '#5d1d0c', '#2d7d2a', '#ff3420', '#5cdd87', '#a259a4', '#e4ac44',
    '#1bede6', '#8798a4', '#d7790f', '#b2c24f', '#de73c2', '#d70a9c', '#25b67',
    '#88e9b8', '#c2b0e2', '#86e98f', '#ae90e2', '#1a806b', '#436a9e', '#0ec0ff',
    '#f812b3', '#b17fc9', '#8d6c2f', '#d3277a', '#2ca1ae', '#9685eb', '#8a96c6',
    '#dba2e6', '#76fc1b', '#608fa4', '#20f6ba', '#07d7f6', '#dce77a', '#77ecca'
  ];

  public color = '';
  public affirmation = '';

  constructor() { }

  ngOnInit() {
    this.affirmation = this.selectRandomAffirmation();
  }

  newAffirmation(): void {
    this.affirmation = this.selectRandomAffirmation();
    // this.color = this.colorList[Math.floor(Math.random() * this.colorList.length)];
    this.color = this.getRandomColor();
  }

  selectRandomAffirmation(): string {
      if (AffirmationsComponent.counter === AFFIRMATIONS.length) {
        AffirmationsComponent.counter = 0;
      }
      return AFFIRMATIONS[AffirmationsComponent.counter++];
  }

    getRandomColor(): string {
    const letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
    }

}
