import {Component, OnInit, ViewChild} from '@angular/core';
import {MatPaginator} from '@angular/material/paginator';
import {MatSort} from '@angular/material/sort';
import {MatTableDataSource} from '@angular/material/table';

export interface PeriodicElement {
  skillKnown: string;
  activity: string;
  skillAvailable: string;
  skillApplied: string;
  effective: string;
}

const ELEMENT_DATA: PeriodicElement[] = [
  {activity: 'Stresstoleranz Skills:', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: 'Sich Ablenken durch...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '1. Puzzles', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '2. Computerspiel (Welches?), Programmieren (Sprache?)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '3. Lesen (Was lesen Sie?)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '4. Ein Instrument spielen (Welches?)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '5. Sport: a. Laufen b. Fahrrad c. Wandern, Walken d. Schwimmen e. Tanzen f. Reiten g. Volleyball h. Fitness Studio i. Boxen j. Krafttraining k. eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '6. Flippern', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '7. Haushaltsarbeit: a. Bügeln b. Putzen c. Holz hacken d. Etwas reparieren e. Aufräumen f. Wäsche waschen g. Kochen h. eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '8. Basteln', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '9. Malen, etwas bemalen (z. B. mit Windowcolors, ,ein Bild, einen Blumentopf, ein Mandala, ein T-Shirt)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '10. Singen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '11. Etwas auswendig lernen (z. B. ein Gedicht, Worte auf Englisch, ein Lied, Adressen, Telefonnummern)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '12. Lieblingsklamotten anziehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '13. Irgendwo hingehen: a. in einen Vergnügungspark b. ins Kino c. ins Theater d. eigenes Beispiel: ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '14. Etwas anschauen: a. in die Waschmaschine b. den mit Holz angefeuerten Ofen c. in ein Aquarium d. aus dem Fenster oder in den Himmel e. eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '15. Renovieren (z. B. ein Zimmer neu streichen, einen Tisch abschleifen.)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '16. Etwas dekorieren', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '17. Mit einem Haustier spielen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '18. Pro-&-Contra-Liste anschauen und lesen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '19. Etwas schreiben: a. Briefe b. Tagebuch c. Gedicht d. Pro-&-Contra-Liste e. Einkaufszettel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '20. Etwas planen: a. einen Ausflug b. eine Reise c. eine besondere Stunde, in der man sich nur Zeit für sich selbst nimmt d. ein Fest e. eine Überraschung f. eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '21.  Eine beliebige Route auf dem Stadtplan einzeichnen und dann entlang dieser Route laufen, joggen, Rad fahren ...', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Unterstützen anderer... ', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '22. Einen Freund besuchen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '23. Einen Brief schreiben', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '24. Jemandem ein Geschenk, eine Blume basteln, malen, oder kaufen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '25. Beim Geschirr spülen helfen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '26. Vokabeln abfragen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '27. Mit einem Freund etwas spielen, z. B. Gesellschaftsspiele …', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '28. E-Mails oder SMS schreiben', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '29. Chatten im Internet', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '30. Beim Wäsche auf-/abhängen, bügeln helfen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '31. Den Tisch decken', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '32. Kleidungsstücke flicken oder Socken stopfen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '33. Zusammen Kuchen backen oder kochen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '34. Jemandem zuhören', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '35. Jemanden ermutigen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Vergleichen...', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '36. Andere bemitleiden sich – ich tue etwas dagegen, dass es mir so schlecht geht!“', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '37. „Die haben die gleiche Chance wie ich, aber sie nutzen sie nicht!“ ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '38.  „Ich habe etwas, was anderenicht haben (z. B. eine Arbeit, eine schöne Wohnung …).“', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '39.  „Im Vergleich zu früher habe ich heute viel erreicht (z. B. ich habe eine Ausbildung absolviert, ich habe ein paar gute Freunde …).“', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Gefühle ersetzen l:', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '(„Wenn ich negative Gefühle habe, versuche ich bewusst, angenehmere Gefühle auszulösen …“)', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '40. Kinderprogramm anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '41. Roman lesen (Welches Buch löst positive Gefühle aus?)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '42. Sich von einem Freund durch Witze etc. aufmuntern lassen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '43. Etwas schreiben (z. B. Tagebuch, Brief, Gedicht)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '44. Sich etwas Gutes tun: a. in einem Café etwas Warmes trinken b. ein neues Tagebuch kaufen c. sich eine Blume schenken d. sich zum Schlafen hinlegen e. eigenes Beispiel: ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '45. Einen Kitschfilm oder Soap operas anschauen (GZSZ, Marienhof, Verbotene Liebe usw.)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Gefühle ersetzen II:', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '(„Bei Wut, Ärger und starker Anspannung kann ich mir eine Erleichterung schaffen durch ...“)', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '46. Papier zerknüllen/zerreißen, ein altes Laken zerreißen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '47. Einen Knoten in ein Handtuch machen und damit auf das Bett oder einen Sessel einschlagen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '48. In den Wald gehen und laut schreien', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '49. Einen Actionfilm anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '50. Gedanken aufschreiben und bis zum nächsten Gespräch mit einem Freund oder bis zur nächsten Therapiestunde weglegen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '51. Gefühle aufschreiben und bis zum nächsten Gespräch mit einem Freund oder bis zur nächsten Therapiestunde weglegen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '52. Leichtes Lächeln', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '53. Gefühlsprotokoll im Manual ausfüllen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '54. Probleme „step by step“ angehen, statt alles auf einmal lösen wollen und überfordert werden', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '55.  Den Skill „Emotionales Leiden loslassen“ einsetzen, Beispiel: ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '56. Dem Gefühl entgegengesetzt handeln; bei welchem Gefühl?', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Beiseite schieben...', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '57.  Schieben Sie eine schmerzhafte Situation beiseite, indem Sie sie eine Weile innerlich verlassen (Wichtig! Setzen Sie sich mit der Situation zu einem späteren Zeitpunkt auseinander!)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '58. Bauen Sie in der Vorstellung zwischen sich und der Situation eine Mauer (Wichtig! Setzen Sie sich mit der Situation zu einem späteren Zeitpunkt auseinander!)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '59. Schreiben Sie ihre Gedanken, Gefühle und Probleme auf einen Zettel, legen Sie den Zettel in eine Schachtel. Heben Sie den Zettel für später auf.', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Hirn-Flick-Flacks...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '60. In 7er-Schritten rückwärts zählen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '61. Stadt-Land-Fluss', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '62. Rätsel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '63. Kreuzworträtsel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '64. Puzzles mit vielen ähnlichen Teilen und ohne Vorlage', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '65. IQ-Test', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '66. „Um die Ecke gedacht“', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '67. Tangram', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '68. Text aus einer anderen Sprache übersetzen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '69. Mathematikaufgaben', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '70. Perlen und Steinchenketten oder dickere Schnur verknoten und wieder auflösen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '71. Büroklammern ineinanderhängen und so schnell wie möglich wieder auseinander machen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '72. Beliebige Punkte auf ein Blatt malen und versuchen durch Verbinden eine Figur zu zeichnen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '73. Fadenspiele', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '74. Kreuzworträtsel selber erstellen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '75. Jonglieren (mit Bällen, mit Seidentüchern)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '76. Im Internet nach etwas suchen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '77. Mit Bauklötzen etwas bauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '78. Einen Zauberwürfel lösen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '79. Memory, Trivial Pursuit, Wer wird Millionär spielen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '80. Ein Bild auf dem Computer malen und dabei die Maus verkehrt herum halten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '81.  Einen Text mit der „falschen“ (linken o. rechten) Hand abschreiben', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Körperempfindungen...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '82. verschiedene Spannungen eines Gummibands, Haargummis spüren, Muskeltraining mit dem Theraband', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '83. Eis oder Eisgelkissen auf die Haut legen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '84. Wurzelbürste', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '85. Laute Musik anhören', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '86. Wechseldusche (warm/kalt) nehmen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '87. Schreien', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '88. Barfuß draußen laufen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '89. Mit nackten Füßen in einem Bach stehen, auf kleinen Murmeln balancieren, auf Kies/Tonkügelchen/Katzenstreu gehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '90. Massage oder Massagegeräte', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '91. Vitamin-Brausetabletten ganz in den Mund nehmen und langsam zergehen lassen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '92. „Ahoi“-Kinderbrausebonbons/-würfel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '93. „Saure Süßigkeiten“ kauen oder zergehen lassen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '94. Übungen an der Wand: Sich mit dem Rücken anlehnen und die Knie im 90°-Winkel aufstellen, einen Tennisball hinter den Rücken klemmen und ihn hoch und runterrollen.', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '95. „Knisterkuhschokolade“ von Milka langsam essen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '96. Muskeln anspannen und loslassen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '97. Krafttraining', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '98. 5 Minuten lang so schnell wie möglich rennen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '99. Handtrainer für Gitarristen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '100. Ammoniak', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '101. Münsterkäse riechen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '102. Chilischoten essen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '103.  Japanisches Heilöl oder „Olbas“ riechen oder auf die Zunge tröpfeln.', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '104. Meerrettich im Glas riechen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '105. Knoblauch pur essen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '106. Sambal Olek riechen (gibt es im Supermarkt)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '107. Fisherman’s Friend“ lutschen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '108. „Airwaves“ oder andere Kaugummis kauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '109. Eukalyptus-Erfrischungstücher (aus der Apotheke) riechen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '110. Frischen Zitronensaft trinken', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '111. Sich von jemandem festhalten oder drücken lassen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '112. Sich selbst umarmen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '113. Etwas Schweres schleppen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '114. In einem kalten See schwimmen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '115. In die Sauna gehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '116. Scharfe Zahnpasta in den Mund nehmen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '117. Eiswürfel unter der Zunge zergehen lassen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '118. Sich mit Bademassagehandschuhen selbst massieren', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '119. Sich an die warme Heizung kuscheln', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '120. Sandsäckchen auf den Bauch legen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '121. Jonglieren', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '122. Gummitwist spielen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '123. Schmerzpunkte fest drücken: Muskelansatz am Schlüsselbein, Bereich zwischen Daumen und Zeigefinger', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Sich selbst beruhigen mit Hilfe der 5 Sinne', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: 'Sehen...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '124. Kaleidoskop', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '125. Kunstpostkarten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '126. Glasbriefbeschwerer mit bunten Motiven anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '127. In ein Museum/einen Zoo gehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '128. Lavalampe betrachten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '129. Aquarium betrachten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '130. Bildbände anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '131. Ins Feuer schauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '132. Dias anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '133. Angenehme Fotos von schönen Erlebnissen anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '134. Blumen ansehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '135. Wolken ziehen sehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '136. Besonders kräftige Farben anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '137. Waschmaschine in Bewegung betrachten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '138. Sterne zuordnen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '139. Aufgenommenes Einzelgespräch auf Video/DVD ansehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '140. Leuchtendes Jojo anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '141. Schütteldose (Schneekugel)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Hören...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '142. Vogelgezwitscher', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '143. Musik (Lieblingsmusik)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '144. Meditationsmusik', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '145. Livekonzert', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '146. Selbst Musik machen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '147. Wellenrauschen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '148. Rauschmuscheln', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '149. Singen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '150. Trommeln', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '151. Naturlaute', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '152. Regentropfen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '153. Geräusche im Haus', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '154. Kassette mit einem Text vom Therapeuten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '155. Kassette mit aufgenommenem Einzelgespräch', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '156. Laute Musik auf Kopfhörern', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '157.  Hörmemory (schwarze Filmdöschen mit etwas füllen z. B. Sand, Kies, Wasser, Mais, Nägel... dann die Döschen mischen und hören, welche zusammengehören – Paare finden, oder sie nach Lautstärke sortieren)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '158. Popcorn in einem Topf mit Deckel machen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '159. Eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Riechen...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '160. Lieblingsparfüm', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '161. Wie riecht es draußen früh morgens?', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '162. Wie riecht es draußen nach einem Regen?', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '163. Frisch gemähtes Gras, Heu, Stroh …', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '164. Blumen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '165. Essen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '166. Früchte', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '167. Bett mit frisch bezogener Bettwäsche', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '168. Frische Kleidungen anziehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '169. Kochen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '170. Ätherische Öle im Duftlämpchen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '171. Duftkerzen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '172. Räucherstäbchen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '173. Seife', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '174. Körpercreme', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '175. Gesichtscreme', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '176. Tigerbalsam', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '177. Knoblauchpizza', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '178. WC-Spray', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '179. Angesägtes Holzstück', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '180. Eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Schmecken...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '181. Frische kräftige Kräuter', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '182. Frisch gepressten Saft', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '183. Bonbons und Schokolade, Kaugummis', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '184. Kuchen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '185. Tee (auch ganz schwach aufgebrüht)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '186. Eissorten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '187. Münsterkäse oder Erdnussbutter', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '188. Selbstgemachtes Popcorn', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '189. Anis oder Kümmel pur ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '190. Eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Fühlen...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '191. Samt', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '192. Seide', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '193. Hund', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '194. Katze', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '195. Pferd', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '196. Flauschdecke', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '197. Weiche oder harte Bürste', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '198. Barfuß laufen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '199. Sich abklopfen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '200. Wärmflasche', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '201. Baden', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '202. Stofftier', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '203. Sandsäckchen (auch auf Heizung erhitzt)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '204. Igelball', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '205. Gummiball', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '206. Vogelfeder', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '207. Massage', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '208. Lieblingshose', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '209. Beim Geschirr spülen das Prickeln der platzenden Schaumbläschen spüren', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '210. Indianisches Drahtspiel oder kleine Drahtspiele zum Bewegen in der Hand', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '211. Lotusblüte', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '212 In einem Geschäft Schuhe anprobieren', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '213. Eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Den Augenblick verändern...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '214.  Fantasie: a. Fantasiereise b. Reiseführer anschauen c. Erinnerungsfotos, Bildbände anschauen d. sich den Feind in einer „löchrigen Unterhose“ vorstellen e. Erinnerungen an angenehme Erlebnisse', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '215. „Sicherer Ort“ (sich an einen bestimmten Ort erinnern, der ein Gefühl von Sicherheit und Geborgenheit auslösen kann, ein bestimmtes Bild visualisieren)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '216.  Sinngebung: a. „Hätte ich das nicht getan, dann...“ (im Nachhinein ist ein Sinn besser zu sehen; sich diesen merken und bei der nächsten schwierigen Situation wieder ins Gedächtnis rufen, auch aufschreiben) b. „Alles hat einen Sinn/Grund, auch wenn ich ihn im Moment nicht sehe ...“ ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '217. Gebet, Meditation: a. in die Kirche gehen und eine Kerze anzünden b. an Dinge denken, für die ich dankbar bin c. spezielle Orte besuchen, Beispiel: f. sich auf den Boden setzen, eine Kerze anzünden und versuchen an nichts zu denken g. Ritual h. beten für das AushaltenKönnen i. eigenes Beispiel: ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '218.  Entspannung: a. Entspannung z. B. nach Jacobson (Muskeln anspannen und wiederloslassen) b. schönes Bad nehmen c. Fußbad d. Massage e. Wärmflasche f. Sauna g. Pause machen h. in ein Café gehen i. schlafen j. lesen k. Lavalampe', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '219.  „Kurzurlaub“ machen: a. eine Viertelstunde Auszeit nehmen und achtsam einen Tee trinken b. ein Stück Kuchen oder einen Joghurt auf der Zunge zergehen lassen c. sich kurz zum Schlafen hinlegen d. eine Zeitung oder ein Buch lesen e. 10 Minuten lang ein Kreuzworträtsel machen f. eine Freundin anrufen g. ein kurzes Hörspiel im Radio anhören', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '220. Probleme „step by step“ angehen, statt alles auf einmal lösen wollen und überfordert werden ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '221. . Schritte in Richtung angenehmer Gefühle, Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '222. Konzentration auf den Augenblick, Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '223. An Pro-&-Contra-Liste denken, oder eine Pro-&-Contra-Liste anschauen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '224. Pro-&-Contra-Liste schreiben', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Längerfristige Stresstoleranzskills...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '225. Radikale Akzeptanz („Im Augenblick kann ich nicht handeln, ich muss die Situation so gut wie möglich aushalten, bis ich eingreifen kann“ ... ein tiefgreifendes Annehmen dessen, was ist – lassen Sie ab vom Kampf mit der Realität). Konkretes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '226. Innere Bereitschaft (Unbeweglichkeit mit innerer Bereitschaft ersetzen, d. h. aufmerksam auf die eigene innere Stimme hören, wach und offen bleiben und aus dieser Haltung heraus handeln (das tun, was notwendig ist). Konkretes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '227. Entscheidung für einen neuen Weg („Ich treffe bewusst eine Entscheidung, dass ich dieses Mal anders handeln werde als früher/als wie ich es gewöhnlich tue. Ich versuche, einen neuen Weg zu gehen, obwohl er teilweise unbekannt ist. Diese Entscheidung muss ich immer wieder treffen.“) Konkretes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '228. Leichtes Lächeln („Durch das Lächeln verändert sich mein Körperzustand, positive Reaktion und Entspannung können einsetzen. Ich lächle nur für mich, es ist nicht ein soziales Lächeln und hat nichts mit anderen Menschen zu tun!“ Also: den Kopf hochnehmen, gerade sitzen, tief durchatmen) Konkretes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Notfallkoffer, mögliche Gegenstände:...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '229. Chilischoten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '230. Vitamin-Brausetabletten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '231. „Ahoi“-Kinderbrause', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '232. Knackfrosch', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '233. Bonbons (süß, sauer, scharf, bitter)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '234. Bürstchen (rauh oder weich)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '235. Kieselstein (kann man in die Schuhe stecken)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '236. Verschiedene Steine (rauh, glatt, stumpf, glitzernd)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '237. Parfümpröbchen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '238. Lippenstifte mit unterschiedlichem Geschmack', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '239. Pro-&-Contra-Liste (leer)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '240. Pro-&-Contra-Liste (schon ausgefüllt)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '241. Gefühlsprotokoll', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '242. Zettel mit Sprüchen (von einer sehr vertrauten Person)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '243. Duftöl', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '244. Kleines Stofftier', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '245. Japanisches Heilöl', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '246. Handgelenk-Gummis', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '247. Kaugummis', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '248. Kleines Geschicklichkeitsspiel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '249. Vogelfeder', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '250. Minikaleidoskop', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '251. Murmel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '252. Erinnerungsfoto', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '253. Adresse und Telefonnummer eines vertrauten Menschen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '254. Spieluhr', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '255. Mini-Igelball', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '256. Softball', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '257. Knetgummi', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '258. Erfrischungstuch', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '259. Besonderer Stift', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '260. Comics', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '261. Ärger-/Wutball', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '262. Kiefernzapfen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '263. Rauschmuschel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '264. Wäscheklammer', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '265. Besondere Taschentücher (z.B. mit lustigen Motiven oder Geruch)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '266. Überraschungseifigur', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '267. Postkarte', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '268. MP3-Player mit Lieblingsmusik / Aufnahme eines Einzelgesprächs', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '269. Knopf, Stein, Tuch von meinem „Lieblingsmenschen“', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '270. Jonglierbälle/-tücher', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '271. Luftballons (als Atemübung aufblasen, bis sie zerplatzen)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '272. Quietschendes Gummitier', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '273. Ammoniak', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '274. Gummiball', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '275. Japanischer Papierball', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '276. Vibrator', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '277. Spielwürfel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '278. Glöckchen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '279. Pfeife', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '280. Kleines Buch', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '281. Kleiner Block mit Rätseln, Mandalas...', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '282. Indianisches Drahtspiel oder kleine Drahtspiele zum Bewegen in der Hand', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '283. Prisma', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '284. Aufmunternde/unterstützende Briefe', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '285. Steinchen oder Perlenkette', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '286. Rosenkranz', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '287. Indexkarte mit Erinnerung an Step by step“-Problemlösung', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '288. Eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Achtsamkeit...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: 'WAS-Fertigkeiten: Wahrnehmen', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '289. Wahrnehmen: a. Die Kamera: Etwas in der Umgebung achtsam sehen ...– was in diesem Augenblick um mich herum geschieht (auswählen, worauf ich achten will) z. B. im Bahnhof, im Café, im botanischen Garten, beim Spaziergang ...– Postkarte/Poster– Waschmachine– Wolken am Himmel, Wasser, Wellen ...– in der Natur: Bäume, Blumen, Insekten ... – Kinder, Tiere, Aquarium, andere Menschen ... – eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '289. Wahrnehmen: b. Der Rekorder: Etwas in der Umgebung achtsam hören ...  – Geräusche von außen ...welche Geräusche sind in diesem Augenblick um mich herum (15 Sekunden bis 30 Minuten lang) – ruhige Musik – nur auf ein bestimmtes Geräusch achten, wenn ich mich mit allen gleichzeitig überfordert fühle (z. B. nur Autos, nur Menschen, nur Vogelstimmen) – in einer bestimmten Situation auf die Geräusche achten (beim Duschen, Kochen, Einschlafen, Straßenbahnfahren) – Hörmemory – eigenes Beispiel: ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '289. Wahrnehmen: c. Die Meisterköchin: Etwas im Mund wahrnehmen ... – Schokolade zergehen lassen – ein Stück Apfel kauen – etwas Saueres – etwas Süßes – Mittagessen – kalte Getränke – warme Getränke – Getränke mit Kohlensäure – eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '289. Wahrnehmen: d. Das Nasentier: Etwas riechen ...– Blumen – Essenzen – Gewürze – Früchte – beim Essen und Trinken – Parfüm in einer Drogerie – Tee-/Kaffeladen – Körpercreme – frische Bäder – beim Spazierengehen(Unterschied zwischen Wald und Wiese) – eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '289. Wahrnehmen: e. Atmende Füße: sich mit geschlossenen Augen barfuß vorwärts tasten, das wahrnehmen, was die Füße empfinden', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '289. Wahrnehmen: f. Tastende Hände: mit geschlossenen Augen Gegenstände (z.B. einen Stein, eine Muschel, Igelball) anfassen, das wahrnehmen, was die Hände empfinden, spüren ... – bei der Gartenarbeit (Blumen, Pflanzen, Humus, Sand) – im Wald oder auf einer Wiese (Wurzeln, Moos, Baumrinde, Gräser) – Teppich – Tiere – verschiedene Bürsten – Kimspiele (Sachen in ein Säckchen tun und später mit einer Hand erfühlen) – Sand-/Kirschsteinsäckchen (auf der Heizung warm gemacht oder im Kühlschrank gekühlt) – verschiedene Stoffe – im Dunkeln im Zimmer herumtasten – den eigenen Körper befühlen – die eigenen oder andere Füße, Schultern, Arme massieren – Fußbad – Tastbuch (Kinderbuch oder selbstgemacht) – mit japanischem Papierball spielen, ohne ihn zu zerdrücken – eigenes Beispiel: – Steine', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '289. Wahrnehmen: g. Den eigenen Atem wahrnehmen: beobachten, wie der Atem hineinströmt, sich ausbreitet und hinausströmt ...– aufmerksam und bewusst ein- und ausatmen– beim Joggen die Atemzüge zählen und versuchen, das Ausatmen zu verlängern– dasselbe im Gehen oder auch in Ruhe tun– tief einatmen, Luft anhalten, bis 4 zählen, dann ganz langsam ausatmen– das tiefe Ein- und Ausatmen mit einem Wort verbinden, z. B. Ent-spannung, Ein-schla-fen (das Wort sollte mindestens 2 Silben haben)– beim Ausatmen mit dem Oberkörper nach unten gehen („Elefant“)– Atemzüge zählen (immer nur bis 10 zählen, dann wieder bei 1 anfangen) – durch den Mund in einen Luftballon oder eine kleine Plastiktüte ausatmen(vor allem, wenn man zu Hyperventilation neigt) – eigenes Beispiel: h. Geschichten hören: Eine Geschichte hören und beobachten, welche Gedanken und Gefühle dabei entstehen, die Gefühle weiterziehen lassen ... i. Gedanken wahrnehmen: Wie Wolken am Himmel oder wie eine Welle, wie das Wasser im Fluss Gedanken wahrnehmen, dann aber nicht an ihnen haften bleiben, sondern sie ziehen lassen ... j. Etwas spüren: z. B. wie sitze ich auf dem Stuhl, wie halte ich meinen Kopf, wie bewege ich mich, was passiert, wenn ich meine Bewegungsabläufe verändere? k. Die eigene Grenze wahrnehmen: sich fragen: Wie geht es mir eigentlich, wie fühlen sich meine Muskeln an, stehe ich unter Stress, wie viel Kraft habe ich noch, welche Bedürfnisse habe ich? l. eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Beschreiben...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '290. a. Reporterin: Mit vielen Adjektiven, möglichst ohne Wertung, das beschreiben, was Sie außerhalb von sich sehen(z. B. ein Zimmer, das, was auf der Straße passiert, Menschen, die mir begegnen, Natur, einen Marktplatz, Gegenstände), als ob Sie eine All-Touristin wären und das Leben auf der Erde überhaupt nicht kennen würden. b. Blinden-Kunst: Eine Abbildung beschreiben, sodass jemand, der blind ist, sich eine genaue Vorstellung von dieser Abbildung machen kann.c. Spiegelbild: Sich vor einen Spiegel stellen und laut beschreiben, was Sie sehen(in der dritten Person) Ich sehe eine junge Frau ...(viele Adjektive verwenden, möglichst ohne Wertung) d. Innen-Reporterin: Das beschreiben, was Sie innerhalb von sich wahrnehmen(z. B. Ihre Gedanken, Gefühle oder körperlichen Reaktionen). e. eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Teilnehmen...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '291. Mikado: ein kompliziertes Muster werfen und Stäbchen heraus-ziehen, ohne dass sich etwas rührt a. Das rohe Ei: ein Ei mit der flachen Seite auf dem Tisch zum Stehen bringen, beobachten Sie dabei Ihre Gedanken b. Zählen: zählen Sie konzentriert im Rhythmus Ihres Atems von 1 bis 10, dann erneut bei 1 beginnen. Wenn Sie von Gedanken und Gefühlen abgelenkt werden, erneut bei 1 beginnen c. Etwas achtsam unternehmen: nur das machen, was ich gerade mache, nicht an das Vorher oder Nachher denken, konzentriert bleiben(z. B. Zähne putzen, Kaffee machen, Spazierengehen, rückwärtslaufen, tanzen, putzen, jonglieren, mit einem Kind zusammen sein, ein Tier streicheln, Gedichte laut lesen) d eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'VWIE-Fertigkeiten...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '292. Annehmend: die Situation annehmen, so wie sie ist, eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '293. Konzentriert: sich auf eine Sache konzentrieren, Konzentration auf den Augenblick, eigenes Beispiel: Wirkungsvoll: das tun, was in der Situation notwendig ist (z. B. wenn es anfängt zu regnen, suche ich mir einen trockenen Unterstand, wenn ich müde bin, mache ich eine Pause, wenn ich satt bin, höre ich auf zu essen) eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Umgang mit Gefühlen...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '294. Angenehme (appetente) Gefühle beschreiben', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '295. Unangenehmen (aversive) Gefühle beschreiben', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '296. Über die Bedeutung und die Auswirkungen von Gefühlen nachdenken', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '297.  Für sich selbst diesen Unterschied deutlich machen: Ich bin nicht das Gefühl, ich habe ein Gefühl', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '298.  Für sich selbst diesen Unterschied deutlich machen: Meine Gedanken sind Produkte meines Geistes. „Die Situation ist bedrohlich“ ist mein Gedanke. Wenn ich eine Realitätsüberprüfung mache, sehe ich, ob eine Gefahr tatsächlich vorhanden ist … ', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '299.  Gefühlsprotokoll ausfüllen (Situation, Gedanken, Physiologie, Motorik, Handlungsimpulse und tatsächliche Handlung beschreiben)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '300. Emotionales Leiden loslassen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '301. Sich an Zeiten erinnern, in denen man sich anders fühlte ... (Fotos, Tagebuch)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '302.  Emotionale Verwundbarkeit verringern: – Krankheiten untersuchen und behandeln lassen, zum Arzt gehen, sich darüber informieren – sich ausgewogen ernähren – regelmäßig etwas trinken,jeden Tag genügend Wasser trinken – Drogen weglassen – regelmäßige Bewegung, um stark zu werden und gesund zu bleiben, Sport in Maßen ausüben – ausreichender Schlaf: dafür sorgen, dass man genügend Schlaf bekommt – Selbstdiziplin: sich jeden Tag etwas vornehmen und es erledigen, um das Gefühl von Kompetenz und Kontrolle zu bekommen.', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '303. Positive Erfahrungen und angenehme Aktivitäten sammeln: Bewusst planen, dass täglich Aktivitäten gemacht werden, die angenehm sein könnten.', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '304. Achtsam sein für positive Erfahrungen (sie wahrnehmen und annehmen)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '305. Emotionale Mythen relativieren(z. B. „Gefühle zu zeigen bedeutet, dass ich schwach bin; Gefühle sind dumm; andere können besser beurteilen, wie es mir geht …“)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '306. Entgegengesetztes Handeln – Handeln gegen die Tendenz des Gefühls:– Angst: Bleiben Sie in der Situation und bekämpfen Sie sie aktiv! – Scham: Bleiben Sie in der Situation, zeigen Sie sich öffentlich, zeigen Sie eine aufrechte Körperhaltung,machen Sie sich klar, dass die Scham ausschließlich in Ihrem Kopf vorgeht, vergewissern Sie sich Ihrer Stärken und Vorteile.– Trauer: Der Trauerprozess sollte abgeschlossen werden, er löst sich dann von selber auf. Bei übermäßiger Trauer empfiehlt es sich, die Trauer auf bestimmte Orte und Zeiten zu begrenzen. Dazu dienen Trauerrituale.– Ärger und Wut: Entspannen Sie die Schulter- und Kinnmuskulatur, atmen Sie ruhig durch, zählen Sie langsam bis 5, bevor Sie etwas erwidern, zaubern Sie ein „mildes Lächeln“ auf Ihre Lippen, versetzen Sie sich in die Position des Gegenübers, sagen Sie etwas Freundliches und Versöhnliches oder gehen Sie der Person aus dem Weg.– Schuld: Bleiben Sie in der Situation bleiben, entschuldigen Sie sich nicht, akzeptieren Sie, dass Dinge auch unkontrollierbar über uns hereinbrechen können. – Ekel: Setzen Sie sich dem Geruch, dem Geschmack oder der Hautwahrnehmung aus und gewöhnen Sie sich daran.– Neid: Nehmen Sie das Gefühl als solches wahr, benennen und akzeptieren Sie es; sammeln Sie Argumente, weshalb der oder die andere es „verdient“ hat, Ihr begehrtes Objekt zu besitzen.– Eifersucht: Erkennen Sie die Eifersucht und nehmen Sie sie an; bemühen Sie sich aktiv um ein freundliches Verhältnis zum vermeintlichen Konkurrenten(Ausnahme: Paarbeziehungen fordern eine Auseinandersetzung)– Depressive Stimmung: Bleiben Sie aktiv', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '307. Etwas wiedergutmachen (bei sich oder bei anderen)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '308. Eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: 'Zwischenmenschliche Skills...', skillKnown: '', skillAvailable: '', skillApplied: '', effective:  ''},
  {activity: '309. Prioritäten setzen: a. Orientierung auf die Selbstachtung b. Orientierung auf die Beziehung c. Orientierung auf das Ziel', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '310.  Hindernisse wahrnehmen: a. Mangel an Fertigkeiten b. störende Gedanken c. beeinträchtigende Gefühle d. Unentschlossenheit e. Umfeld', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '311. Um etwas bitten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '312. Nein sagen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '313. Situation beschreiben („Ich fühle mich gerade ..., weil ich sehe, dass ...“)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '314. Ich-Botschaften (statt Du-Botschaften)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '315. Auf Wünschen beharren', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '316. Kratzer auf der Schallplatte (etwas wiederholen)', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '317. Andere Menschen bestärken, wenn sie etwas machen, was für Sie selbst sinnvoll und positiv ist', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '318. Angriffe evtl. ignorieren', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '319. Verhandeln', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '320. Den Spieß umdrehen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '321. Freundlich sein', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '322. Keine Drohung', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '323. Keine Bewertung', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '324. Fairness einsetzen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '325. Humor einsetzen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '326. Keine Rechtfertigungen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '327. Eigene Werte beachten', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '328. Aufrichtigkeit', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '329. Den Partner auf der gleichen Ebene ansprechen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '330. Von sich selbst und seinen Gefühlen sprechen, statt zu verallgemeinern und „man tut“, „man denkt“ zu sagen ...', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '331. Sich störende Grundannahmen bewusst machen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '332. Gegenargumente zu störenden Gedanken finden ...', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '333. Sich die eigenen Rechte und die anderer bewusst machen', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '334. Die Aussage des anderen wiederholen, um zu prüfen, ob ich ihn richtig verstanden habe', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
  {activity: '335. Eigenes Beispiel:', skillKnown: 'Ja / Nein', skillAvailable: 'Ja / Nein', skillApplied: '0 1 2 3 4', effective:  '0 1 2 3 4'},
];

/**
 * @title Data table with pagination, and filtering.
 */

@Component({
  selector: 'app-skills-collection',
  templateUrl: './skills-collection.component.html',
  styleUrls: ['./skills-collection.component.scss']
})
export class SkillsCollectionComponent implements OnInit {
  displayedColumns: string[] = ['activity', 'skillKnown', 'skillAvailable', 'skillApplied', 'effective'];
  dataSource: MatTableDataSource<PeriodicElement>;

  @ViewChild(MatPaginator, {static: true}) paginator: MatPaginator;
  // @ViewChild(MatSort, {static: true}) sort: MatSort;

  constructor() {
    // Assign the data to the data source for the table to render
    this.dataSource = new MatTableDataSource(ELEMENT_DATA);
  }

  ngOnInit() {
    this.dataSource.paginator = this.paginator;
    // this.dataSource.sort = this.sort;
  }

  applyFilter(filterValue: string) {
    this.dataSource.filter = filterValue.trim().toLowerCase();

    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }

}